<a href="https://colab.research.google.com/github/Plee47/Python_Pandas_ex/blob/main/Exemplo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Primeiro exemplo de manipulacao de python Pandas

In [ ]:
import pandas as pd

comb_df = pd.read_excel("combdf.xlsx")

In [ ]:
print(comb_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [ ]:
display(comb_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [ ]:
display(comb_df.head(15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA

In [ ]:
# Comandos Dataframe.shape e Dataframe.describe()

# Mostrar o numero de linhas e colunas

print(comb_df.shape)

#So as linhas

print(comb_df.shape[0])

(168409, 16)
168409

In [ ]:
display(comb_df.describe())

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [ ]:
print(comb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [ ]:
revendas = comb_df["Revenda"]
display(revendas)

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [ ]:
produtos_df = comb_df[['Revenda', 'Municipio', 'Produto', 'Valor de Venda']]
display(produtos_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

In [ ]:
display(comb_df.loc[1:5])

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA

In [ ]:
gaso_df = comb_df.loc[comb_df['Produto'] =='GASOLINA']
display(gaso_df)

display(gaso_df['Valor de Venda'].max())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA
19,N,AM,ITACOATIARA,MARCOS ANTONIO DA SILVA CABRAL,03.019.535/0001-00,AVENIDA PARQUE,1012,NaN,CENTRO,69100-000,GASOLINA,2021-11-01,6.990,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168392,SE,SP,BAURU,AUTO POSTO KM BAURU LTDA,30.550.652/0001-60,RUA CAMPOS SALLES,22160,NaN,VILA FALCAO,17050-000,GASOLINA,2021-12-31,6.199,NaN,R$ / litro,RAIZEN
168394,SE,MG,ITUIUTABA,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,45.236.791/0107-40,AVENIDA GOVERNADOR JOSE DE MAGALHAES PINTO,131,NaN,MARIA VILELA,38301-078,GASOLINA,2021-12-31,6.899,NaN,R$ / litro,IPIRANGA
168399,SE,RJ,CAMPOS DOS GOYTACAZES,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,20.641.704/0001-50,AVENIDA ALBERTO TORRES,512,CONJ 512/520 ANEXO ESQUINA COM A ...,PARQUE LEOPOLDINA,28051-287,GASOLINA,2021-12-31,7.090,NaN,R$ / litro,BRANCA
168403,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,GASOLINA,2021-12-31,6.799,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

7.999

In [ ]:
display(comb_df[['Revenda', 'Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                         8.99
dtype: object

In [ ]:
gaso_df = comb_df.loc[(comb_df['Produto'] == 'GASOLINA') & (comb_df['Municipio'] == 'INDAIATUBA')]
display(gaso_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
12773,SE,SP,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,07.712.794/0001-65,AVENIDA ENGENHEIRO FABIO ROBERTO BARNABE,3399,NaN,BOM PRINCIPIO,13345-690,GASOLINA,2021-11-03,6.477,NaN,R$ / litro,VIBRA ENERGIA
12777,SE,SP,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,05.758.861/0001-57,AVENIDA FRANCISCO DE PAULA LEITE,71,NaN,SANTA CRUZ,13343-040,GASOLINA,2021-11-03,6.397,NaN,R$ / litro,VIBRA ENERGIA
12782,SE,SP,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,07.591.385/0001-58,AVENIDA FRANCISCO DE PAULA LEITE,2089,NaN,JD. TROPICAL,13344-565,GASOLINA,2021-11-03,6.279,NaN,R$ / litro,RAIZEN
12787,SE,SP,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,60.342.466/0001-05,RUA DOS INDAIAS,1331,NaN,VILA BRIZOLA,13344-000,GASOLINA,2021-11-03,6.099,NaN,R$ / litro,RAIZEN
12789,SE,SP,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,48.176.259/0001-14,RUA PADRE BENTO PACHECO,893,NaN,CENTRO,13330-000,GASOLINA,2021-11-03,6.299,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159498,SE,SP,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,09.372.323/0001-80,RUA PADRE BENTO PACHECO,1.229,NaN,CENTRO,13330-020,GASOLINA,2021-12-28,6.239,NaN,R$ / litro,BRANCA
160593,SE,SP,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,18.043.211/0001-77,RUA JACOB LYRA,1.25,NaN,PARQUE DAS NACOES,13346-010,GASOLINA,2021-12-28,5.999,NaN,R$ / litro,VIBRA ENERGIA
160807,SE,SP,INDAIATUBA,POSTO RECREIO OURO LTDA,19.781.349/0001-36,AVENIDA FRANCISCO DE PAULA LEITE,3689,NaN,RECREIO CAMPESTRE JOIA,13346-615,GASOLINA,2021-12-28,6.399,NaN,R$ / litro,RAIZEN
160995,SE,SP,INDAIATUBA,POSTO DOS ESTEVES LTDA,20.763.169/0001-00,AVENIDA ITORORO,160,NaN,CENTRO,13330-055,GASOLINA,2021-12-28,6.499,NaN,R$ / litro,IPIRANGA
161799,SE,SP,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,30.253.289/0001-11,AVENIDA PRESIDENTE KENNEDY,496,NaN,CIDADE NOVA I,13334-170,GASOLINA,2021-12-28,6.299,NaN,R$ / litro,RAIZEN

In [ ]:
gaso_df = comb_df.loc[(comb_df['Produto'] == 'GASOLINA') & (comb_df['Municipio'] == 'INDAIATUBA'), 
                                         ['Municipio', 'Revenda', 'Data da Coleta', 'Produto', 'Valor de Venda']]
display(gaso_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
gaso_df['Imposto'] = gaso_df['Valor de Venda'] * 0.10
display(gaso_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda,Imposto
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477,0.6477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397,0.6397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279,0.6279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099,0.6099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299,0.6299
...,...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239,0.6239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999,0.5999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399,0.6399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499,0.6499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299,0.6299

In [ ]:
gaso_df = gaso_df.drop("Imposto", axis=1)
display(gaso_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
gaso_df = gaso_df.dropna(how='all')
display(gaso_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
gaso_df = gaso_df.dropna(how='all', axis=1)
display(gaso_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
gaso_df['Imposto'] = gaso_df['Valor de Venda'] * 0.10
gaso_df['Imposto'] = gaso_df['Imposto'].fillna(gaso_df['Imposto'].mean())
display(gaso_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda,Imposto
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477,0.6477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397,0.6397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279,0.6279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099,0.6099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299,0.6299
...,...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239,0.6239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999,0.5999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399,0.6399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499,0.6499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299,0.6299

In [ ]:
media_por_prod = comb_df[['Produto', 'Valor de Venda']].groupby('Produto').mean().round(2)
display(media_por_prod)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [ ]:
comb_df['Ativo'] = True
print(comb_df.info())
display(comb_df.head)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

<bound method NDFrame.head of        Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira  \
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

        Ativo
0        True
1        True
2        True
3        True
4        True
...       ...
168404   True
168405   True
168406   True
168407   True
168408   True

[168409 rows x 17 columns]>

In [ ]:
media_por_prod.to_excel("media_por_prod.xlsx", sheet_name = 'Media de valor dos produtos', index = False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive